menu:
  主页: /
  归档: /archives
  分类: /categories
  标签: /tags

# duoshuo comment
duoshuo: false
duoshuo_name:

# disqus comment
disqus: true
disqus_shortname: llbetter

# google analytics
googleTrackId:
